# Generated by Django 4.2.1 on 2023-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='course',
            field=models.CharField(choices=[('appetizer', 'appetizer'), ('breakfast', 'breakfast'), ('dessert', 'dessert'), ('dinner', 'dinner'), ('lunch', 'lunch'), ('main course', 'main course'), ('one pot dish', 'one pot dish'), ('side dish', 'side dish'), ('snack', 'snack')], default='appetizer', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='diet',
            field=models.CharField(choices=[('diabetic friendly', 'diabetic friendly'), ('eggetarian', 'eggetarian'), ('gluten free', 'gluten free'), ('high protein non vegetarian', 'high protein non vegetarian'), ('high protein vegetarian', 'high protein vegetarian'), ('no onion no garlic (sattvic)', 'no onion no garlic (sattvic)'), ('non vegetarian', 'non vegetarian'), ('vegan', 'vegan'), ('vegetarian', 'vegetarian')], default='diet', max_length=28),
        ),
    ]
